services:
  dashdot:
    image: mauricenino/dashdot:latest
    container_name: dashdot
    restart: always
    privileged: true
    ports:
      - '3001:3001'
    volumes:
      - /:/mnt/host:ro
    environment:
      DASHDOT_PORT: 3001
      DASHDOT_ENABLE_CPU_TEMPS: true
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: true
      DASHDOT_WIDGET_LIST: 'os,cpu,storage,ram,network'