services:
  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    ports:
      - 8989:8989
    volumes:
      - ./config:/config
      - /mnt/series/downloads:/downloads
      - /mnt/series/series:/data

