include:
  - path: "plex/docker-compose.plex.yml"
  - path: "dash/docker-compose.dash.yml"
  - path: "homarr/docker-compose.homarr.yml"
  - path: "portainer/docker-compose.portainer.yml"
  - path: "prowlarr/docker-compose.prowlarr.yml"
  - path: "qbittorrent/docker-compose.qbittorrent.yml"
  - path: "radarr/docker-compose.radarr.yml"
  - path: "sonarr/docker-compose.sonarr.yml"
  - path: "watchtower/docker-compose.watchtower.yml"