services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
    network_mode: host
    volumes:
      - ./config:/config
      - /mnt/series/series:/series
      - /mnt/movies/movies:/movies
    devices: 
      - /dev/dri:/dev/dri