services:
  portainer:
    image: portainer/agent:latest
    container_name: portainer_agent
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.soc
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host