services:
  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    ports:
      - 7878:7878
    volumes:
      - ./config:/config
      - /mnt/series/downloads:/downloads
      - /mnt/movies/movies:/data