services:
  flaresolverr:
    image: 21hsmw/flaresolverr:nodriver
    container_name: flaresolverr
    restart: unless-stopped
    user: $PUID:$PGID
    environment:
      - LOG_LEVEL=info
      - LANG=en_US
    ports:
      - 8191:8191
