services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    command: --cleanup --interval 86400
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock