services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - '80:3001'
    volumes:
      - /:/mnt/host:ro
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: true
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: true
      DASHDOT_WIDGET_LIST: 'os,cpu,storage,ram,network'